/**
 * Demo engine — lets the app run fully client-side (GitHub Pages live demo).
 *
 * - The ML prediction runs the SAME exported model JSON in the browser
 *   (generated by ai-model/export_model.py, verified against sklearn).
 * - Auth + saved predictions live in localStorage instead of MongoDB.
 *
 * Enabled when the app is built with `vite build --mode demo`
 * (frontend/.env.demo sets VITE_DEMO_MODE=true).
 */

import collegesData from "../data/colleges.js";

export const IS_DEMO = import.meta.env.VITE_DEMO_MODE === "true";

const K_USERS = "acap_demo_users";
const K_TOKEN = "acap_demo_token";
const K_PREDICTIONS = "acap_demo_predictions";

const FEATURES = ["gre", "toefl", "rating", "sop", "lor", "cgpa", "research"];

/* ------------------------- ML model inference ------------------------- */

let modelPromise = null;

function loadDemoModel() {
  if (!modelPromise) {
    modelPromise = fetch(`${import.meta.env.BASE_URL}model.json`).then((r) => {
      if (!r.ok) throw new Error("Failed to load demo model");
      return r.json();
    });
  }
  return modelPromise;
}

/** Runs the exported GradientBoosting model in the browser. */
export async function demoPredictChance(profile) {
  const model = await loadDemoModel();
  const x = FEATURES.map((f) => Number(profile[f]));
  const xs = x.map((v, i) => (v - model.scaler.mean[i]) / model.scaler.scale[i]);

  let raw = model.init;
  for (const tree of model.trees) {
    let node = 0;
    while (tree.childrenLeft[node] !== -1) {
      const goLeft = xs[tree.feature[node]] <= tree.threshold[node];
      node = goLeft ? tree.childrenLeft[node] : tree.childrenRight[node];
    }
    raw += model.learningRate * tree.value[node];
  }
  return Math.round(Math.min(Math.max(raw, 0.01), 0.99) * 1000) / 1000;
}

/** Same fit scoring as backend/services/collegeService.js. */
export function demoComputeFit(college, profile) {
  const greFit = 1 - Math.min(Math.abs(profile.gre - college.avgGRE) / 40, 1);
  const toeflFit = 1 - Math.min(Math.abs(profile.toefl - college.avgTOEFL) / 30, 1);
  const cgpaFit = 1 - Math.min(Math.abs(profile.cgpa - college.avgCGPA) / 2.5, 1);
  const meetsMin = profile.cgpa >= college.minCGPA ? 1 : 0.3;
  return Math.round((greFit * 0.4 + toeflFit * 0.2 + cgpaFit * 0.3 + meetsMin * 0.1) * 100);
}

export function demoMatchColleges(profile, limit = 8) {
  return collegesData
    .map((c) => ({ college: c._id, name: c.name, fitScore: demoComputeFit(c, profile) }))
    .sort((a, b) => b.fitScore - a.fitScore)
    .slice(0, limit);
}

/* ------------------------------ storage ------------------------------ */

const read = (key, fallback) => {
  try {
    return JSON.parse(localStorage.getItem(key)) ?? fallback;
  } catch {
    return fallback;
  }
};
const write = (key, value) => localStorage.setItem(key, JSON.stringify(value));

const uid = () => `demo-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;

/* -------------------------------- auth -------------------------------- */

export function demoRegister({ name, email, password }) {
  const users = read(K_USERS, []);
  if (users.some((u) => u.email === email.toLowerCase())) {
    throw new Error("An account with this email already exists");
  }
  const user = { _id: uid(), name, email: email.toLowerCase(), password };
  users.push(user);
  write(K_USERS, users);
  const token = uid();
  localStorage.setItem(K_TOKEN, token);
  return { _id: user._id, name: user.name, email: user.email, token };
}

export function demoLogin({ email, password }) {
  const users = read(K_USERS, []);
  const user = users.find(
    (u) => u.email === (email || "").toLowerCase() && u.password === password
  );
  if (!user) throw new Error("Invalid email or password");
  const token = uid();
  localStorage.setItem(K_TOKEN, token);
  return { _id: user._id, name: user.name, email: user.email, token };
}

export function demoGetMe() {
  const token = localStorage.getItem(K_TOKEN);
  if (!token) throw new Error("Not logged in");
  const userId = token.split("-").slice(0, 4).join("-");
  const found = read(K_USERS, []).find((u) => u._id === userId);
  if (!found) throw new Error("Session expired");
  return { _id: found._id, name: found.name, email: found.email };
}

export function demoLogout() {
  localStorage.removeItem(K_TOKEN);
}

export function demoGetProfile() {
  return { user: demoGetMe(), student: null };
}

export function demoUpdateProfile({ name }) {
  const users = read(K_USERS, []);
  const me = demoGetMe();
  const user = users.find((u) => u._id === me._id);
  if (user && name) {
    user.name = name;
    write(K_USERS, users);
    return { user: { _id: user._id, name: user.name, email: user.email }, student: null };
  }
  return { user: me, student: null };
}

/* ----------------------------- predictions ----------------------------- */

export async function demoCreatePrediction(profile) {
  const chanceOfAdmit = await demoPredictChance(profile);
  const matchedColleges = demoMatchColleges(profile, 8);
  const prediction = {
    _id: uid(),
    profile,
    chanceOfAdmit,
    source: "model",
    matchedColleges,
    createdAt: new Date().toISOString(),
  };
  const all = read(K_PREDICTIONS, []);
  all.unshift(prediction);
  write(K_PREDICTIONS, all);
  return prediction;
}

export function demoGetMyPredictions() {
  return read(K_PREDICTIONS, []);
}

export function demoDeletePrediction(id) {
  write(
    K_PREDICTIONS,
    read(K_PREDICTIONS, []).filter((p) => p._id !== id)
  );
  return { message: "Prediction deleted" };
}

/* ------------------------------- colleges ------------------------------- */

export function demoGetColleges(params = {}) {
  let list = [...collegesData];
  if (params.q) {
    const q = params.q.toLowerCase();
    list = list.filter(
      (c) => c.name.toLowerCase().includes(q) || c.location.toLowerCase().includes(q)
    );
  }
  if (params.sort === "ranking") list.sort((a, b) => a.ranking - b.ranking);
  else list.sort((a, b) => a.name.localeCompare(b.name));
  return list;
}

export function demoGetCollege(id) {
  const college = collegesData.find((c) => c._id === id);
  if (!college) throw new Error("College not found");
  return college;
}

